### ISSUE TITLE
Offline Report Generation

### ISSUE THREAD

**Issue by rtivera** [OneIdentity/ansible-authentication-services#7]
We are using these playbooks on a disconnected network.  However, the playbooks run but reports aren't generating the tables when we open the html page in a browser.  Is there a something that needs to be included with the playbooks? i.e., javascripts, etc.

<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>

**Comment by llnagy76** [comment]
Currently you can not use the html reports in a disconnected environment because the generated html files use external .css and .js files and in order to display the reports properly the browser must be able to download these files from the internet.
What you can use in a disconnected environment are the csv reports that contain no links to external files.
